### ISSUE TITLE
MySQL Set-Up

### ISSUE THREAD

**Issue by kellyloomis** [kellyloomis/Project-3#8]

**Comment by Kist221** [comment]
Would you say this is complete? or still in progress? @jjdavid14

**Comment by Kist221** [comment]
Still need a table for reviews/feedback/surveys associated to Employees

**Comment by jjdavid14** [comment]
This is still in progress, not sure what other columns I'll have to add. I'm currently working on another table for REVIEW which will be associated with an EMPLOYEE so that a history of REVIEW can be retrieved.
